#version 
version: '3.1'

#setup
services:
#Php
  php:
    depends_on:
      - db
    image: rifdirectory/php-dev-rif
    restart: always
    ports:
      - 5000:80
    volumes:
    - ~/Documents/web-dev:/var/www/html 

#Phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 5050:80
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 64M

#mysql
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - myapp:/var/lib/mysql
    environment:
      #MYSQL_DATABASE: istana
      MYSQL_ROOT_PASSWORD: advance
      MYSQL_PASSWORD: advance
      
 #cache
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass advance
    volumes:
      - cache:/data     

volumes:
  myapp:
    
